---
-
  name: Deploy Docker container
  hosts: ansibleslave
  become: true
  tasks:
    - name: update apt
      command: sudo apt-get update

    - name: install docker
      command: sudo apt install -y docker.io

    - name: start docker service
      command: sudo systemctl start docker

    - name: deploy todo application
      command: sudo docker run -itd -p 5000:5000 umahanty/flaskapp
